// This file has been autogenerated from a class added in the UI designer.

using System;
using Autofac;
using testviper.Core.Domains.Transfers.View;
using UIKit;

namespace testviper.iOS.Domains.Transfers.View
{
	public partial class FirstViewController : UIViewController, ITransfersFirstView
	{
        public FirstViewController()
        {
        }

        public FirstViewController (IntPtr handle) : base (handle)
		{
		}
        
        public void SetSpacesError()
        {
            
        }
    }
}
